# Generated by Django 3.1.3 on 2021-04-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicRequirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicrequirement',
            name='note2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='basicrequirement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
