# Generated by Django 3.1.3 on 2021-05-04 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicRequirements', '0002_auto_20210501_0156'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basicrequirement',
            table='basicRequirements',
        ),
    ]
