# Generated by Django 3.1.3 on 2021-05-07 03:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_learningobjective'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohort', '0002_auto_20210505_0217'),
        ('BasicRequirements', '0003_auto_20210505_0217'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basicrequirement',
            unique_together={('student_name', 'staff_name', 'cohort', 'subject')},
        ),
        migrations.AlterModelTable(
            name='basicrequirement',
            table='basicrquirements',
        ),
    ]
