# Generated by Django 3.1.3 on 2021-05-07 20:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0002_auto_20210505_0217'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0002_subject_learningobjective'),
        ('BasicRequirements', '0004_auto_20210507_0642'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basicrequirement',
            unique_together={('student_name', 'cohort', 'subject')},
        ),
    ]
