# Generated by Django 3.1.3 on 2021-04-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0001_initial'),
        ('week', '0001_initial'),
        ('subjects', '0002_subject_learningobjective'),
        ('cohort', '0001_initial'),
        ('ActiveStatuse', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activestate',
            unique_together={('subject', 'day', 'week', 'cohort')},
        ),
    ]
