# Generated by Django 3.1.3 on 2021-05-04 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cohort',
            table='cohort',
        ),
    ]
