# Generated by Django 3.1.3 on 2021-04-13 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_newuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
