# Generated by Django 3.2 on 2021-04-15 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohort', '0001_initial'),
        ('week', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refactored', models.BooleanField(default=False)),
                ('mark', models.IntegerField(default=0)),
                ('comments', models.TextField(default='')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohort.cohort')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=' staffname+', to=settings.AUTH_USER_MODEL)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentname+', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='week.week')),
            ],
            options={
                'db_table': 'Assessments',
            },
        ),
    ]
