# Generated by Django 3.1.3 on 2021-05-05 21:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohort', '0002_auto_20210505_0217'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('week', '0001_initial'),
        ('Assessment', '0003_auto_20210505_0217'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('student_name', 'cohort', 'week')},
        ),
    ]
