# Generated by Django 3.2 on 2021-04-15 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('days', '0001_initial'),
        ('week', '0001_initial'),
        ('cohort', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warmups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('notes', models.TextField(default='')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cohort.cohort')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='days.day')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=' staffname+', to=settings.AUTH_USER_MODEL)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentname+', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='week.week')),
            ],
            options={
                'db_table': 'Warmups',
            },
        ),
    ]
