# Generated by Django 3.1.3 on 2021-05-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warmups', '0003_auto_20210501_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='warmups',
            name='title',
            field=models.TextField(default='NotSolved'),
        ),
    ]
