# Generated by Django 3.1.3 on 2021-05-04 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warmups', '0008_auto_20210503_0004'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='warmups',
            table='warmups',
        ),
    ]
